services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CPSIT\MyraCloudConnector\:
    resource: '../Classes/*'
    exclude: ['../Classes/Domain/{DTO,Enum}']

  CPSIT\MyraCloudConnector\Command\MyraCloudClearCommand:
    tags:
      - name: 'console.command'
        command: 'myracloud:clear'
        description: 'TYPO3/Myra Cloud Interface'
        hidden: false
        schedulable: false

  # @todo Migrate to attribute once support for TYPO3 v12 is dropped
  CPSIT\MyraCloudConnector\EventListener\ExternalClearCacheButtonListener:
    tags:
      - name: event.listener
        identifier: 'cpsit/myra-cloud-connector/external-clear-cache-button'

  # @todo Migrate to attribute once support for TYPO3 v12 is dropped
  CPSIT\MyraCloudConnector\EventListener\ExternalClearCacheFileListListener:
    tags:
      - name: event.listener
        identifier: 'cpsit/myra-cloud-connector/external-clear-cache-file-list'

  # @todo Migrate to attribute once support for TYPO3 v12 is dropped
  CPSIT\MyraCloudConnector\EventListener\ExternalClearCacheMenuItemListener:
    tags:
      - name: event.listener
        identifier: 'cpsit/myra-cloud-connector/external-clear-cache-menu-item'

  # @todo Migrate to attribute once support for TYPO3 v12 is dropped
  CPSIT\MyraCloudConnector\EventListener\ExternalClearResourceCacheListener:
    tags:
      - name: event.listener
        identifier: 'cpsit/myra-cloud-connector/external-clear-resource-cache'
